### ISSUE TITLE
Warnings coming please fix and release an update soon

### ISSUE THREAD

**Issue by Dhara61** [ImaginateSolutions/custom-payment-gateways-woocommerce#6]
WC_Gateway_Alg_Custom_Template::$is_wc_version_below_3 is deprecated
wp-content/plugins/custom-payment-gateways-woocommerce/includes/class-wc-gateway-alg-custom.php:37

WC_Gateway_Alg_Custom_Template::$instructions_in_email is deprecated
wp-content/plugins/custom-payment-gateways-woocommerce/includes/class-wc-gateway-alg-custom.php:412

WC_Gateway_Alg_Custom_Template::$min_amount is deprecated
wp-content/plugins/custom-payment-gateways-woocommerce/includes/class-wc-gateway-alg-custom.php:414

WC_Gateway_Alg_Custom_Template::$custom_return_url is deprecated
wp-content/plugins/custom-payment-gateways-woocommerce/includes/class-wc-gateway-alg-custom.php:420

Reference: https://wordpress.org/support/topic/deprecated-warnings-in-query-monitor/

**Comment by dhruvins** [comment]
Errors addressed and update released hence closing this
